# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PROGRAMMING\DESKTOP-APP\Inventory_System_via_QRcode [TUP-C_UITC]\GUI [UI_FILES]\addremoveitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addremoveitemWindow(object):
    def setupUi(self, addremoveitemWindow):
        addremoveitemWindow.setObjectName("addremoveitemWindow")
        addremoveitemWindow.resize(501, 671)
        font = QtGui.QFont()
        font.setPointSize(7)
        addremoveitemWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PROGRAMMING\\DESKTOP-APP\\Inventory_System_via_QRcode [TUP-C_UITC]\\GUI [UI_FILES]\\icons/INVENTORY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addremoveitemWindow.setWindowIcon(icon)
        addremoveitemWindow.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.centralwidget = QtWidgets.QWidget(addremoveitemWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonUpdateinventoryConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonUpdateinventoryConfirm.setEnabled(False)
        self.pushButtonUpdateinventoryConfirm.setGeometry(QtCore.QRect(70, 530, 361, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUpdateinventoryConfirm.sizePolicy().hasHeightForWidth())
        self.pushButtonUpdateinventoryConfirm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButtonUpdateinventoryConfirm.setFont(font)
        self.pushButtonUpdateinventoryConfirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonUpdateinventoryConfirm.setStyleSheet("background-color: rgb(195, 29, 57);\n"
"color: rgb(255, 255, 255);")
        self.pushButtonUpdateinventoryConfirm.setObjectName("pushButtonUpdateinventoryConfirm")
        self.labelUpdateInventoryTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateInventoryTitle.setGeometry(QtCore.QRect(120, 210, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelUpdateInventoryTitle.setFont(font)
        self.labelUpdateInventoryTitle.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelUpdateInventoryTitle.setObjectName("labelUpdateInventoryTitle")
        self.labelUpdateInventoryLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateInventoryLogo.setGeometry(QtCore.QRect(210, 100, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelUpdateInventoryLogo.sizePolicy().hasHeightForWidth())
        self.labelUpdateInventoryLogo.setSizePolicy(sizePolicy)
        self.labelUpdateInventoryLogo.setStyleSheet("image: url(:/icons/icons/BOX.png);\n"
"background-color: rgb(48, 48, 48);\n"
"border-radius: 10px;")
        self.labelUpdateInventoryLogo.setText("")
        self.labelUpdateInventoryLogo.setObjectName("labelUpdateInventoryLogo")
        self.pusButtonUpdateInventoryBack = QtWidgets.QPushButton(self.centralwidget)
        self.pusButtonUpdateInventoryBack.setGeometry(QtCore.QRect(20, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pusButtonUpdateInventoryBack.setFont(font)
        self.pusButtonUpdateInventoryBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pusButtonUpdateInventoryBack.setStyleSheet("background-color: rgb(195, 29, 57);\n"
"color: rgb(255, 255, 255);")
        self.pusButtonUpdateInventoryBack.setObjectName("pusButtonUpdateInventoryBack")
        self.comboBoxUpdateInventoryEquipment = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxUpdateInventoryEquipment.setEnabled(True)
        self.comboBoxUpdateInventoryEquipment.setGeometry(QtCore.QRect(70, 370, 361, 40))
        self.comboBoxUpdateInventoryEquipment.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);\n"
"editable: rgb(65, 65, 65);")
        self.comboBoxUpdateInventoryEquipment.setEditable(False)
        self.comboBoxUpdateInventoryEquipment.setCurrentText("")
        self.comboBoxUpdateInventoryEquipment.setMaxVisibleItems(50)
        self.comboBoxUpdateInventoryEquipment.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBoxUpdateInventoryEquipment.setObjectName("comboBoxUpdateInventoryEquipment")
        self.spinBoxUpdateInventoryQty = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxUpdateInventoryQty.setEnabled(False)
        self.spinBoxUpdateInventoryQty.setGeometry(QtCore.QRect(70, 460, 361, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBoxUpdateInventoryQty.setFont(font)
        self.spinBoxUpdateInventoryQty.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBoxUpdateInventoryQty.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.spinBoxUpdateInventoryQty.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBoxUpdateInventoryQty.setMinimum(1)
        self.spinBoxUpdateInventoryQty.setMaximum(50)
        self.spinBoxUpdateInventoryQty.setObjectName("spinBoxUpdateInventoryQty")
        self.labelUpdateInventoryQty = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateInventoryQty.setGeometry(QtCore.QRect(70, 430, 161, 20))
        self.labelUpdateInventoryQty.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelUpdateInventoryQty.setObjectName("labelUpdateInventoryQty")
        self.labelUpdateInventoryCard = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateInventoryCard.setGeometry(QtCore.QRect(20, 60, 461, 591))
        self.labelUpdateInventoryCard.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border-radius: 10px;")
        self.labelUpdateInventoryCard.setText("")
        self.labelUpdateInventoryCard.setObjectName("labelUpdateInventoryCard")
        self.groupBoxUpdateInventoryChooseaction = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxUpdateInventoryChooseaction.setGeometry(QtCore.QRect(70, 270, 361, 51))
        self.groupBoxUpdateInventoryChooseaction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupBoxUpdateInventoryChooseaction.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.groupBoxUpdateInventoryChooseaction.setObjectName("groupBoxUpdateInventoryChooseaction")
        self.radioButtonUpdateInventoryAdditem = QtWidgets.QRadioButton(self.groupBoxUpdateInventoryChooseaction)
        self.radioButtonUpdateInventoryAdditem.setGeometry(QtCore.QRect(30, 20, 111, 17))
        self.radioButtonUpdateInventoryAdditem.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.radioButtonUpdateInventoryAdditem.setObjectName("radioButtonUpdateInventoryAdditem")
        self.radioButtonUpdateInventoryDeleteItem = QtWidgets.QRadioButton(self.groupBoxUpdateInventoryChooseaction)
        self.radioButtonUpdateInventoryDeleteItem.setGeometry(QtCore.QRect(250, 20, 91, 17))
        self.radioButtonUpdateInventoryDeleteItem.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.radioButtonUpdateInventoryDeleteItem.setObjectName("radioButtonUpdateInventoryDeleteItem")
        self.radioButtonUpdateInventoryUpdateItem = QtWidgets.QRadioButton(self.groupBoxUpdateInventoryChooseaction)
        self.radioButtonUpdateInventoryUpdateItem.setGeometry(QtCore.QRect(130, 20, 111, 17))
        self.radioButtonUpdateInventoryUpdateItem.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.radioButtonUpdateInventoryUpdateItem.setObjectName("radioButtonUpdateInventoryUpdateItem")
        self.labelUpdateInventoryEquipment = QtWidgets.QLabel(self.centralwidget)
        self.labelUpdateInventoryEquipment.setGeometry(QtCore.QRect(70, 350, 61, 20))
        self.labelUpdateInventoryEquipment.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelUpdateInventoryEquipment.setObjectName("labelUpdateInventoryEquipment")
        self.labelUpdateInventoryCard.raise_()
        self.pushButtonUpdateinventoryConfirm.raise_()
        self.labelUpdateInventoryTitle.raise_()
        self.labelUpdateInventoryLogo.raise_()
        self.pusButtonUpdateInventoryBack.raise_()
        self.comboBoxUpdateInventoryEquipment.raise_()
        self.spinBoxUpdateInventoryQty.raise_()
        self.labelUpdateInventoryQty.raise_()
        self.groupBoxUpdateInventoryChooseaction.raise_()
        self.labelUpdateInventoryEquipment.raise_()
        addremoveitemWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(addremoveitemWindow)
        QtCore.QMetaObject.connectSlotsByName(addremoveitemWindow)
        addremoveitemWindow.setTabOrder(self.comboBoxUpdateInventoryEquipment, self.spinBoxUpdateInventoryQty)
        addremoveitemWindow.setTabOrder(self.spinBoxUpdateInventoryQty, self.pushButtonUpdateinventoryConfirm)
        addremoveitemWindow.setTabOrder(self.pushButtonUpdateinventoryConfirm, self.pusButtonUpdateInventoryBack)

    def retranslateUi(self, addremoveitemWindow):
        _translate = QtCore.QCoreApplication.translate
        addremoveitemWindow.setWindowTitle(_translate("addremoveitemWindow", "TUP-C UITC INVENTORY SYSTEM"))
        self.pushButtonUpdateinventoryConfirm.setText(_translate("addremoveitemWindow", "CONFIRM"))
        self.labelUpdateInventoryTitle.setText(_translate("addremoveitemWindow", "UPDATE INVENTORY"))
        self.pusButtonUpdateInventoryBack.setText(_translate("addremoveitemWindow", "BACK"))
        self.labelUpdateInventoryQty.setText(_translate("addremoveitemWindow", "Enter Quantity: (Max. Qty is 50)"))
        self.groupBoxUpdateInventoryChooseaction.setTitle(_translate("addremoveitemWindow", "Choose Action"))
        self.radioButtonUpdateInventoryAdditem.setText(_translate("addremoveitemWindow", "Add Item"))
        self.radioButtonUpdateInventoryDeleteItem.setText(_translate("addremoveitemWindow", "Delete Item"))
        self.radioButtonUpdateInventoryUpdateItem.setText(_translate("addremoveitemWindow", "Update Item"))
        self.labelUpdateInventoryEquipment.setText(_translate("addremoveitemWindow", "Equipment:"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addremoveitemWindow = QtWidgets.QMainWindow()
    ui = Ui_addremoveitemWindow()
    ui.setupUi(addremoveitemWindow)
    addremoveitemWindow.show()
    sys.exit(app.exec_())
