# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PROGRAMMING\DESKTOP-APP\Inventory_System_via_QRcode [TUP-C_UITC]\GUI [UI_FILES]\index.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_indexWindow(object):
    def setupUi(self, indexWindow):
        indexWindow.setObjectName("indexWindow")
        indexWindow.resize(743, 745)
        indexWindow.setMinimumSize(QtCore.QSize(743, 745))
        indexWindow.setMaximumSize(QtCore.QSize(743, 745))
        indexWindow.setGeometry(600, 150, 743, 745)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PROGRAMMING\\DESKTOP-APP\\Inventory_System_via_QRcode [TUP-C_UITC]\\GUI [UI_FILES]\\icons/INVENTORY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        indexWindow.setWindowIcon(icon)
        indexWindow.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.centralwidget = QtWidgets.QWidget(indexWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonIndexLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonIndexLogin.setGeometry(QtCore.QRect(70, 600, 600, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.pushButtonIndexLogin.setFont(font)
        self.pushButtonIndexLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonIndexLogin.setStyleSheet("background-color: rgb(195, 29, 57);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonIndexLogin.setObjectName("pushButtonIndexLogin")
        self.indexCard = QtWidgets.QLabel(self.centralwidget)
        self.indexCard.setEnabled(True)
        self.indexCard.setGeometry(QtCore.QRect(20, 20, 700, 700))
        self.indexCard.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border-radius: 14px;")
        self.indexCard.setText("")
        self.indexCard.setObjectName("indexCard")
        self.indexLogo = QtWidgets.QLabel(self.centralwidget)
        self.indexLogo.setGeometry(QtCore.QRect(310, 90, 135, 135))
        self.indexLogo.setStyleSheet("color: rgb(255, 255, 255);\n"
"image: url(:/icons/icons/INVENTORY.png);\n"
"background-color: rgb(48, 48, 48);")
        self.indexLogo.setObjectName("indexLogo")
        self.pushButtonIndexSignup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonIndexSignup.setGeometry(QtCore.QRect(70, 510, 600, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        self.pushButtonIndexSignup.setFont(font)
        self.pushButtonIndexSignup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonIndexSignup.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(37, 37, 37);\n"
"\n"
"")
        self.pushButtonIndexSignup.setObjectName("pushButtonIndexSignup")
        self.indexTitle = QtWidgets.QLabel(self.centralwidget)
        self.indexTitle.setGeometry(QtCore.QRect(180, 230, 391, 121))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.indexTitle.setFont(font)
        self.indexTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(48, 48, 48);")
        self.indexTitle.setObjectName("indexTitle")
        self.indexCard.raise_()
        self.pushButtonIndexLogin.raise_()
        self.indexLogo.raise_()
        self.pushButtonIndexSignup.raise_()
        self.indexTitle.raise_()
        indexWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(indexWindow)
        QtCore.QMetaObject.connectSlotsByName(indexWindow)

    def retranslateUi(self, indexWindow):
        _translate = QtCore.QCoreApplication.translate
        indexWindow.setWindowTitle(_translate("indexWindow", "Welcome - TUP-C UITC INVENTORY SYSTEM"))
        self.pushButtonIndexLogin.setText(_translate("indexWindow", "LOG IN"))
        self.indexLogo.setText(_translate("indexWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonIndexSignup.setText(_translate("indexWindow", "SIGN UP"))
        self.indexTitle.setText(_translate("indexWindow", "<html><head/><body><p align=\"center\">TUP-C UITC</p><p align=\"center\">INVENTORY SYSTEM</p></body></html>"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    indexWindow = QtWidgets.QMainWindow()
    ui = Ui_indexWindow()
    ui.setupUi(indexWindow)
    indexWindow.show()
    sys.exit(app.exec_())
