# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PROGRAMMING\DESKTOP-APP\Inventory_System_via_QRcode [TUP-C_UITC]\GUI [UI_FILES]\qrcodegenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_qrcodegeneratorWindow(object):
    def setupUi(self, qrcodegeneratorWindow):
        qrcodegeneratorWindow.setObjectName("qrcodegeneratorWindow")
        qrcodegeneratorWindow.resize(482, 611)
        qrcodegeneratorWindow.setMinimumSize(QtCore.QSize(482, 611))
        qrcodegeneratorWindow.setMaximumSize(QtCore.QSize(482, 611))
        qrcodegeneratorWindow.setGeometry(720, 200, 482, 611)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\PROGRAMMING\\DESKTOP-APP\\Inventory_System_via_QRcode [TUP-C_UITC]\\GUI [UI_FILES]\\icons/INVENTORY.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        qrcodegeneratorWindow.setWindowIcon(icon)
        qrcodegeneratorWindow.setStyleSheet("background-color: rgb(223, 223, 223);")
        self.centralwidget = QtWidgets.QWidget(qrcodegeneratorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelQrcodeCard = QtWidgets.QLabel(self.centralwidget)
        self.labelQrcodeCard.setEnabled(True)
        self.labelQrcodeCard.setGeometry(QtCore.QRect(20, 60, 440, 531))
        self.labelQrcodeCard.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border-radius: 14px;")
        self.labelQrcodeCard.setText("")
        self.labelQrcodeCard.setObjectName("labelQrcodeCard")
        self.comboBoxQrcodeItemCode = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxQrcodeItemCode.setGeometry(QtCore.QRect(90, 300, 291, 41))
        self.comboBoxQrcodeItemCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBoxQrcodeItemCode.setStyleSheet("border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.comboBoxQrcodeItemCode.setEditable(False)
        self.comboBoxQrcodeItemCode.setObjectName("comboBoxQrcodeItemCode")
        self.comboBoxQrcodeItemCode.addItem("")
        self.labelQRcodeNumbering = QtWidgets.QLabel(self.centralwidget)
        self.labelQRcodeNumbering.setGeometry(QtCore.QRect(160, 360, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelQRcodeNumbering.setFont(font)
        self.labelQRcodeNumbering.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelQRcodeNumbering.setObjectName("labelQRcodeNumbering")
        self.labelQrcodeTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelQrcodeTitle.setGeometry(QtCore.QRect(90, 210, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelQrcodeTitle.setFont(font)
        self.labelQrcodeTitle.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelQrcodeTitle.setObjectName("labelQrcodeTitle")
        self.labelQRcodeEnd = QtWidgets.QLabel(self.centralwidget)
        self.labelQRcodeEnd.setGeometry(QtCore.QRect(240, 420, 21, 31))
        self.labelQRcodeEnd.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelQRcodeEnd.setObjectName("labelQRcodeEnd")
        self.labelQRcodeStart = QtWidgets.QLabel(self.centralwidget)
        self.labelQRcodeStart.setGeometry(QtCore.QRect(70, 420, 31, 31))
        self.labelQRcodeStart.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelQRcodeStart.setObjectName("labelQRcodeStart")
        self.pushButtonQrcodeGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonQrcodeGenerate.setGeometry(QtCore.QRect(70, 490, 341, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQrcodeGenerate.sizePolicy().hasHeightForWidth())
        self.pushButtonQrcodeGenerate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButtonQrcodeGenerate.setFont(font)
        self.pushButtonQrcodeGenerate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonQrcodeGenerate.setStyleSheet("background-color: rgb(195, 29, 57);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonQrcodeGenerate.setObjectName("pushButtonQrcodeGenerate")
        self.spinBoxQrcodeStart = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxQrcodeStart.setGeometry(QtCore.QRect(110, 410, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBoxQrcodeStart.setFont(font)
        self.spinBoxQrcodeStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBoxQrcodeStart.setStyleSheet("border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.spinBoxQrcodeStart.setMinimum(1)
        self.spinBoxQrcodeStart.setMaximum(300)
        self.spinBoxQrcodeStart.setObjectName("spinBoxQrcodeStart")
        self.spinBoxQrcodeEnd = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxQrcodeEnd.setGeometry(QtCore.QRect(270, 410, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.spinBoxQrcodeEnd.setFont(font)
        self.spinBoxQrcodeEnd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBoxQrcodeEnd.setStyleSheet("border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(65, 65, 65);")
        self.spinBoxQrcodeEnd.setMinimum(1)
        self.spinBoxQrcodeEnd.setMaximum(300)
        self.spinBoxQrcodeEnd.setObjectName("spinBoxQrcodeEnd")
        self.labelQrcodeLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelQrcodeLogo.setGeometry(QtCore.QRect(190, 80, 111, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelQrcodeLogo.sizePolicy().hasHeightForWidth())
        self.labelQrcodeLogo.setSizePolicy(sizePolicy)
        self.labelQrcodeLogo.setStyleSheet("image: url(:/icons/icons/qrcode.png);\n"
"background-color: rgb(48, 48, 48);")
        self.labelQrcodeLogo.setText("")
        self.labelQrcodeLogo.setObjectName("labelQrcodeLogo")
        self.labelQRcodeEquipment = QtWidgets.QLabel(self.centralwidget)
        self.labelQRcodeEquipment.setGeometry(QtCore.QRect(90, 280, 141, 16))
        self.labelQRcodeEquipment.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);")
        self.labelQRcodeEquipment.setObjectName("labelQRcodeEquipment")
        self.pushButtonQrcodeBack = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonQrcodeBack.setGeometry(QtCore.QRect(30, 20, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonQrcodeBack.setFont(font)
        self.pushButtonQrcodeBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonQrcodeBack.setStyleSheet("background-color: rgb(195, 29, 57);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pushButtonQrcodeBack.setObjectName("pushButtonQrcodeBack")
        qrcodegeneratorWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(qrcodegeneratorWindow)
        QtCore.QMetaObject.connectSlotsByName(qrcodegeneratorWindow)

    def retranslateUi(self, qrcodegeneratorWindow):
        _translate = QtCore.QCoreApplication.translate
        qrcodegeneratorWindow.setWindowTitle(_translate("qrcodegeneratorWindow", "QR Code Generator - TUP-C UITC INVENTORY SYSTEM"))
        self.comboBoxQrcodeItemCode.setCurrentText(_translate("qrcodegeneratorWindow", "Click here to choose Equipment"))
        self.comboBoxQrcodeItemCode.setItemText(0, _translate("qrcodegeneratorWindow", "Click here to choose Equipment"))
        self.labelQRcodeNumbering.setText(_translate("qrcodegeneratorWindow", "Set QR Code Numbering"))
        self.labelQrcodeTitle.setText(_translate("qrcodegeneratorWindow", "QR CODE GENERATOR"))
        self.labelQRcodeEnd.setText(_translate("qrcodegeneratorWindow", "End"))
        self.labelQRcodeStart.setText(_translate("qrcodegeneratorWindow", "Start"))
        self.pushButtonQrcodeGenerate.setText(_translate("qrcodegeneratorWindow", "GENERATE"))
        self.labelQRcodeEquipment.setText(_translate("qrcodegeneratorWindow", "Item Code"))
        self.pushButtonQrcodeBack.setText(_translate("qrcodegeneratorWindow", "BACK"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    qrcodegeneratorWindow = QtWidgets.QMainWindow()
    ui = Ui_qrcodegeneratorWindow()
    ui.setupUi(qrcodegeneratorWindow)
    qrcodegeneratorWindow.show()
    sys.exit(app.exec_())
